-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 22:22:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Centre Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Centre Students` (
  `Student_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Graduation_Year` INT NULL,
  `Class_ID (FK)` INT NULL,
  `Student_Email` VARCHAR(100) NULL,
  PRIMARY KEY (`Student_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instructors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instructors` (
  `Instructor_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Instructor_Email` VARCHAR(100) NULL,
  PRIMARY KEY (`Instructor_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Classes` (
  `Class_ID` INT NOT NULL,
  `Category` VARCHAR(45) NULL,
  `Number` INT NULL,
  `Section` VARCHAR(45) NULL,
  `Year` INT NULL,
  `Semester` VARCHAR(45) NULL,
  `Instructor_ID (FK)` INT NULL,
  PRIMARY KEY (`Class_ID`),
  CONSTRAINT `Instructor_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Instructors` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skills` (
  `Skill_Name` VARCHAR(45) NOT NULL,
  `Prerequisite_Skill (FK)` VARCHAR(45) NULL,
  PRIMARY KEY (`Skill_Name`),
  CONSTRAINT `Class_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Classes` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Questions` (
  `Question_ID` INT NOT NULL,
  `Text` VARCHAR(500) NULL,
  `Skill_Name (FK)` VARCHAR(45) NULL,
  PRIMARY KEY (`Question_ID`),
  CONSTRAINT `Skill_Name`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Skills` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answers` (
  `Answer_ID` INT NOT NULL,
  `Is_Correct` VARCHAR(45) NULL,
  `Answer_Text` VARCHAR(500) NULL,
  `Question_ID (FK)` INT NULL,
  PRIMARY KEY (`Answer_ID`),
  CONSTRAINT `Question_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Questions` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prerequisites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prerequisites` (
  `Skill_Name (CPK/FK)` VARCHAR(45) NOT NULL,
  `Prerequisite_Skill (CPK/FK)` VARCHAR(45) NULL,
  PRIMARY KEY (`Skill_Name (CPK/FK)`),
  INDEX `fk_Prerequisites_Skills1_idx` (`Prerequisite_Skill (CPK/FK)` ASC),
  CONSTRAINT `Skill_Name`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Skills` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Prerequisite_Skill`
    FOREIGN KEY (`Prerequisite_Skill (CPK/FK)`)
    REFERENCES `mydb`.`Skills` (`Skill_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_Responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_Responses` (
  `Student_Response_ID` INT NOT NULL,
  `Response_Text` VARCHAR(500) NULL,
  `Student_ID (FK)` INT NULL,
  `Question_ID (FK)` INT NULL,
  PRIMARY KEY (`Student_Response_ID`),
  CONSTRAINT `Question_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Questions` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Student_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Centre Students` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`Student Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student Classes` (
  `Student_ID (CPK/FK)` INT NOT NULL,
  `Class_ID (CPK/FK)` INT NOT NULL,
  PRIMARY KEY (`Student_ID (CPK/FK)`, `Class_ID (CPK/FK)`),
  CONSTRAINT `Student_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Centre Students` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Class_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Classes` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
